targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      freezed:
        generate_for:
          include:
            - lib/domain/entities/**.dart
        options:
          union_key: type
          union_value_case: snake
